apiDir: "../liferay-rest-api/src/main/java"
apiPackagePath: "com.code81.tmo.liferay.rest"
application:
    baseURI: "/liferay-rest"
    className: "LiferayRestApplication"
    name: "LiferayRest"
author: "Mahmoud.Khalil"
clientDir: "../liferay-rest-client/src/main/java"
testDir: "../liferay-rest-test/src/testIntegration/java"